# Generated by Django 6.0.6 on 2026-06-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='portfolio/images/')),
                ('github_url', models.URLField(blank=True, help_text='Link to source code')),
                ('live_url', models.URLField(blank=True, help_text='Link to live demo (if any)')),
                ('technologies', models.CharField(help_text='E.g., Django, Python, Bootstrap', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
