# Generated by Django 6.0.6 on 2026-07-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/certificates/'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='duration',
            field=models.CharField(blank=True, help_text='e.g., June 2026 - Present', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='order',
            field=models.IntegerField(default=0, help_text='Lower numbers appear first'),
        ),
    ]
