# Generated by Django 6.0.6 on 2026-07-10 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_internship_certificate_alter_internship_duration_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
